In [4]:
import pandas as pd
import numpy as np

In [5]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David"],
    "hours": [5, 2, 8, 6],
    "score": [85, 70, 95, 88]
}

df = pd.DataFrame(data)

df

      name  hours  score
0    Alice      5     85
1      Bob      2     70
2  Charlie      8     95
3    David      6     88

In [6]:
print(df.shape)
type(df)

(4, 3)

pandas.core.frame.DataFrame

In [6]:
df.head()

      name  hours  score
0    Alice      5     85
1      Bob      2     70
2  Charlie      8     95
3    David      6     88

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   hours   4 non-null      int64
 2   score   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [8]:
df.describe()

       hours      score
count   4.00   4.000000
mean    5.25  84.500000
std     2.50  10.535654
min     2.00  70.000000
25%     4.25  81.250000
50%     5.50  86.500000
75%     6.50  89.750000
max     8.00  95.000000

In [9]:
df.columns

Index(['name', 'hours', 'score'], dtype='object')

In [10]:
type(df["score"])

pandas.core.series.Series

In [11]:
df["score"]

0    85
1    70
2    95
3    88
Name: score, dtype: int64

In [12]:
df["score"][0]

np.int64(85)

In [13]:
type(df["score"][0])

numpy.int64

In [7]:
## data selection
print(df.iloc[0]) # select the first row by index
print(df.loc[0]) # select the first row by label

name     Alice
hours        5
score       85
Name: 0, dtype: object
name     Alice
hours        5
score       85
Name: 0, dtype: object

In [20]:
df["score"]

df.iloc[:, 2]

0    85
1    70
2    95
3    88
Name: score, dtype: int64

In [ ]:
## boolean filtering
## hours >= 5
df[df["hours"] >= 5]

      name  hours  score
0    Alice      5     85
2  Charlie      8     95
3    David      6     88

In [30]:
## score between 80 and 90
df[(df["score"]<=90) & (df["score"]>=80)]

    name  hours  score
0  Alice      5     85
3  David      6     88

In [33]:
## data cleaning
data = {
    "name": ["Alice","Bob","Charlie","David"],
    "hours": [5, None, 8, 6],
    "score": [85,70,None,88]
}

df_missing = pd.DataFrame(data)

df_missing

      name  hours  score
0    Alice    5.0   85.0
1      Bob    NaN   70.0
2  Charlie    8.0    NaN
3    David    6.0   88.0

In [34]:
df_missing.isnull()

    name  hours  score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [36]:
df_missing.dropna()

    name  hours  score
0  Alice    5.0   85.0
3  David    6.0   88.0

In [ ]:
df_missing["hours"].fillna(
    df_missing["hours"].mean()
)

In [8]:
df.sort_values("score")
df.sort_values("score",ascending=False)
df.sort_values("score",ascending=False,inplace=True)

In [41]:
df["score_pct"] = df["score"] / 100
df.shape

(4, 4)